POST http://localhost:8080/api/attributions/create
Content-Type: application/json

{
  "utilisateur": {
    "id": 2
  },
  "recompense": {
    "id": 1
  },
  "contexteAttribution": "Récompense pour avoir complété 10 tâches"
}
