### Correct
POST http://localhost:8080/api/confrontationpiege/create
Content-Type: application/json
X-Utilisateur-Email: lazyjoe@example.com

{
  "piege": {
    "id": 1
  },
  "resultat": "SUCCES",
  "points": 10,
  "commentaire": "J'ai réussi à éviter la fausse réunion Zoom !"
}