### Correct
POST http://localhost:8080/api/tacheaeviter/create
Content-Type: application/json
X-Utilisateur-Email: Michelle2@miage.com

{
  "titre": "Ma tâche impérative",
  "dateLimite": "2026-04-23T18:25:43.511Z",
  "consequences": "La planète s'arrête",
  "description": "Ce que j'ai repousé précieusement à demain"
}