POST http://localhost:8080/api/recompenses/create
Content-Type: application/json

{
  "titre": "Récompense du mois",
  "description": "Décernée à la meilleure excuse du mois",
  "conditionsObtention": "Avoir plus de 50 votes",
  "niveau": null,
  "type": "BADGE"
}