### Correct
POST http://localhost:8080/api/utilisateur/create
Content-Type: application/json

{
  "pseudo": "Michelle",
  "email": "Michelle2@miage.com",
  "role": "PROCRASTINATEUR_EN_HERBE"
}

### Correct
POST http://localhost:8080/api/utilisateur/create
X-Utilisateur-Email: el.flemardo@miage.fr
Content-Type: application/json

{
  "pseudo": "LeEfficace",
  "email": "piege1337@irit.fr",
  "role": "ANTIPROCRASTINATEUR_REPENTI"
}